# Generated by Django 2.2 on 2020-01-03 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='genre',
            field=models.IntegerField(choices=[(1, 'Not selected'), (2, 'Comedy'), (3, 'Action'), (4, 'Beauty'), (5, 'Science'), (6, 'Other')], default=1),
        ),
    ]
