# Generated by Django 2.2 on 2019-12-23 18:40

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=50)),
                ('comment_text', models.CharField(blank=True, max_length=200, null=True)),
                ('comment_date', models.DateTimeField(default=datetime.datetime(2019, 12, 23, 18, 40, 40, 177465, tzinfo=utc))),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 18, 40, 40, 177027, tzinfo=utc)),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.Article')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapps.Article'),
        ),
    ]
