# Generated by Django 2.2 on 2019-12-23 18:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0005_auto_20191223_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 18, 59, 19, 194079, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 18, 59, 19, 194496, tzinfo=utc)),
        ),
    ]
