# Generated by Django 2.2 on 2019-12-23 19:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('myapps', '0006_auto_20191223_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 19, 19, 9, 450326, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 23, 19, 19, 9, 450763, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='like',
            name='counter',
            field=models.IntegerField(default=1),
        ),
    ]
